<?php
/**
 * Created by PhpStorm.
 * User: ralph
 * Date: 16.02.17
 * Time: 17:08
 */

/**
 * Import field formatters.
 */
require_once 'includes/field_formatter.lib.inc';

/**
 * Import image styles (ImageMagick styles), if imagemagick module is installed
 */
if (module_exists('imagemagick')) {
  require_once 'includes/image_style.lib.inc';
}

/**
 * Useful Webform enhancements.
 */
if (module_exists('webform')) {
  require_once 'includes/webform.lib.inc';
}

/**
 * Import all social node importers.
 */
if (module_exists('twitter') || module_exists('instagram_social_feed')) {
  require_once 'includes/social_nodes.importer.inc';
}


/* --------------------------------------------------
 * Hooks implementations
 * --------------------------------------------------*/

/**
 * Implements hook_theme().
 */
function pxl_hooks_theme() {
  return array(
    // The theme function that our formatter uses:
    'pxl_hooks_date_von_bis_formatter' => array(
      'variables' => array('element' => NULL),
      'file' => 'includes/field_formatter.lib.inc',
    ),
    'pxl_hooks_date_start_ende_formatter' => array(
      'variables' => array('element' => NULL),
      'file' => 'includes/field_formatter.lib.inc',
    ),
  );
}



/* --------------------------------------------------
 * Bookings table action link
 * --------------------------------------------------*/
/**
 * Add an action link to the bookings view allowing to add a new calendar event.
 */
function pxl_hooks_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  switch($root_path){
    case 'admin/content/bookings':
      $item = menu_get_item('node/add/calendar_event');
      if ($item['access']) {
        $item['title'] = t('Add booking event');
        $item['href'] = 'node/add/calendar-event';
        $data['actions']['output'][] = array(
          '#theme' => 'menu_local_action',
          '#link' => $item,
        );
      }
      break;
  }
}
